/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedLearningTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "balanceOf"
      | "checkIn"
      | "confidentialProtocolId"
      | "createCourse"
      | "generateSkillProof"
      | "getApproved"
      | "getCheckInStats"
      | "getCourse"
      | "getScore"
      | "getSkillProof"
      | "getStudyData"
      | "getStudyDays"
      | "isApprovedForAll"
      | "name"
      | "ownerOf"
      | "recordStudyData"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setBaseURI"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "transferFrom"
      | "uploadScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "CheckInRecorded"
      | "CoursePassed"
      | "ScoreUploaded"
      | "SkillProofGenerated"
      | "StudyDataRecorded"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIn",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCourse",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "generateSkillProof",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCheckInStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSkillProof",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudyData",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudyDays",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordStudyData",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setBaseURI", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadScore",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkIn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateSkillProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCheckInStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCourse", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSkillProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudyData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudyDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordStudyData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBaseURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadScore",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CheckInRecordedEvent {
  export type InputTuple = [
    student: AddressLike,
    consecutiveDays: BigNumberish
  ];
  export type OutputTuple = [student: string, consecutiveDays: bigint];
  export interface OutputObject {
    student: string;
    consecutiveDays: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoursePassedEvent {
  export type InputTuple = [student: AddressLike, courseId: BigNumberish];
  export type OutputTuple = [student: string, courseId: bigint];
  export interface OutputObject {
    student: string;
    courseId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUploadedEvent {
  export type InputTuple = [
    student: AddressLike,
    courseId: BigNumberish,
    handle: BytesLike
  ];
  export type OutputTuple = [student: string, courseId: bigint, handle: string];
  export interface OutputObject {
    student: string;
    courseId: bigint;
    handle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SkillProofGeneratedEvent {
  export type InputTuple = [
    student: AddressLike,
    skillId: BigNumberish,
    courseId: BigNumberish
  ];
  export type OutputTuple = [
    student: string,
    skillId: bigint,
    courseId: bigint
  ];
  export interface OutputObject {
    student: string;
    skillId: bigint;
    courseId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StudyDataRecordedEvent {
  export type InputTuple = [student: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [student: string, timestamp: bigint];
  export interface OutputObject {
    student: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedLearningTracker extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedLearningTracker;
  waitForDeployment(): Promise<this>;

  interface: EncryptedLearningTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  checkIn: TypedContractMethod<
    [studyTimeEuint32: BytesLike, studyTimeProof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createCourse: TypedContractMethod<
    [
      courseName: string,
      thresholdEuint32: BytesLike,
      thresholdProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  generateSkillProof: TypedContractMethod<
    [courseId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getCheckInStats: TypedContractMethod<
    [student: AddressLike],
    [[bigint, bigint] & { consecutiveDays: bigint; lastCheckInDay: bigint }],
    "view"
  >;

  getCourse: TypedContractMethod<
    [courseId: BigNumberish],
    [
      [string, string, boolean] & {
        name: string;
        thresholdHandle: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getScore: TypedContractMethod<
    [student: AddressLike, courseId: BigNumberish],
    [[string, string] & { scoreHandle: string; passedHandle: string }],
    "view"
  >;

  getSkillProof: TypedContractMethod<
    [student: AddressLike, skillId: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        courseId: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getStudyData: TypedContractMethod<
    [student: AddressLike, timestamp: BigNumberish],
    [
      [string, string, boolean] & {
        studyTimeHandle: string;
        focusLevelHandle: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getStudyDays: TypedContractMethod<[student: AddressLike], [bigint[]], "view">;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  recordStudyData: TypedContractMethod<
    [
      timestamp: BigNumberish,
      studyTimeEuint32: BytesLike,
      studyTimeProof: BytesLike,
      focusLevelEuint32: BytesLike,
      focusLevelProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setBaseURI: TypedContractMethod<[newBaseURI: string], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  uploadScore: TypedContractMethod<
    [courseId: BigNumberish, scoreEuint32: BytesLike, scoreProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkIn"
  ): TypedContractMethod<
    [studyTimeEuint32: BytesLike, studyTimeProof: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createCourse"
  ): TypedContractMethod<
    [
      courseName: string,
      thresholdEuint32: BytesLike,
      thresholdProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "generateSkillProof"
  ): TypedContractMethod<[courseId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCheckInStats"
  ): TypedContractMethod<
    [student: AddressLike],
    [[bigint, bigint] & { consecutiveDays: bigint; lastCheckInDay: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCourse"
  ): TypedContractMethod<
    [courseId: BigNumberish],
    [
      [string, string, boolean] & {
        name: string;
        thresholdHandle: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<
    [student: AddressLike, courseId: BigNumberish],
    [[string, string] & { scoreHandle: string; passedHandle: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSkillProof"
  ): TypedContractMethod<
    [student: AddressLike, skillId: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        courseId: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudyData"
  ): TypedContractMethod<
    [student: AddressLike, timestamp: BigNumberish],
    [
      [string, string, boolean] & {
        studyTimeHandle: string;
        focusLevelHandle: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudyDays"
  ): TypedContractMethod<[student: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "recordStudyData"
  ): TypedContractMethod<
    [
      timestamp: BigNumberish,
      studyTimeEuint32: BytesLike,
      studyTimeProof: BytesLike,
      focusLevelEuint32: BytesLike,
      focusLevelProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseURI"
  ): TypedContractMethod<[newBaseURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uploadScore"
  ): TypedContractMethod<
    [courseId: BigNumberish, scoreEuint32: BytesLike, scoreProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "CheckInRecorded"
  ): TypedContractEvent<
    CheckInRecordedEvent.InputTuple,
    CheckInRecordedEvent.OutputTuple,
    CheckInRecordedEvent.OutputObject
  >;
  getEvent(
    key: "CoursePassed"
  ): TypedContractEvent<
    CoursePassedEvent.InputTuple,
    CoursePassedEvent.OutputTuple,
    CoursePassedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUploaded"
  ): TypedContractEvent<
    ScoreUploadedEvent.InputTuple,
    ScoreUploadedEvent.OutputTuple,
    ScoreUploadedEvent.OutputObject
  >;
  getEvent(
    key: "SkillProofGenerated"
  ): TypedContractEvent<
    SkillProofGeneratedEvent.InputTuple,
    SkillProofGeneratedEvent.OutputTuple,
    SkillProofGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "StudyDataRecorded"
  ): TypedContractEvent<
    StudyDataRecordedEvent.InputTuple,
    StudyDataRecordedEvent.OutputTuple,
    StudyDataRecordedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "CheckInRecorded(address,uint256)": TypedContractEvent<
      CheckInRecordedEvent.InputTuple,
      CheckInRecordedEvent.OutputTuple,
      CheckInRecordedEvent.OutputObject
    >;
    CheckInRecorded: TypedContractEvent<
      CheckInRecordedEvent.InputTuple,
      CheckInRecordedEvent.OutputTuple,
      CheckInRecordedEvent.OutputObject
    >;

    "CoursePassed(address,uint256)": TypedContractEvent<
      CoursePassedEvent.InputTuple,
      CoursePassedEvent.OutputTuple,
      CoursePassedEvent.OutputObject
    >;
    CoursePassed: TypedContractEvent<
      CoursePassedEvent.InputTuple,
      CoursePassedEvent.OutputTuple,
      CoursePassedEvent.OutputObject
    >;

    "ScoreUploaded(address,uint256,bytes32)": TypedContractEvent<
      ScoreUploadedEvent.InputTuple,
      ScoreUploadedEvent.OutputTuple,
      ScoreUploadedEvent.OutputObject
    >;
    ScoreUploaded: TypedContractEvent<
      ScoreUploadedEvent.InputTuple,
      ScoreUploadedEvent.OutputTuple,
      ScoreUploadedEvent.OutputObject
    >;

    "SkillProofGenerated(address,uint256,uint256)": TypedContractEvent<
      SkillProofGeneratedEvent.InputTuple,
      SkillProofGeneratedEvent.OutputTuple,
      SkillProofGeneratedEvent.OutputObject
    >;
    SkillProofGenerated: TypedContractEvent<
      SkillProofGeneratedEvent.InputTuple,
      SkillProofGeneratedEvent.OutputTuple,
      SkillProofGeneratedEvent.OutputObject
    >;

    "StudyDataRecorded(address,uint256)": TypedContractEvent<
      StudyDataRecordedEvent.InputTuple,
      StudyDataRecordedEvent.OutputTuple,
      StudyDataRecordedEvent.OutputObject
    >;
    StudyDataRecorded: TypedContractEvent<
      StudyDataRecordedEvent.InputTuple,
      StudyDataRecordedEvent.OutputTuple,
      StudyDataRecordedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
